### ISSUE TITLE
GetDevices Error

### ISSUE THREAD

**Issue by xxyy3130** [mfakane/rawinput-sharp#20]
RawInputDevice.GetDevices() InvalidDeviceId.

**Comment by oyashchyshyn** [comment]
Have same issue:

`System.InvalidOperationException: InvalidDeviceId
   at Linearstar.Windows.RawInput.Native.CfgMgr32.EnsureSuccess(ConfigReturnValue result)
   at Linearstar.Windows.RawInput.RawInputDevice.GetAttributesFromCfgMgr()
   at Linearstar.Windows.RawInput.RawInputDevice.GetAttributes()`
   
  Is it possible to skip device that have an error with Id, because problem of one devices I cannot get others

**Comment by mingyangzhu** [comment]
me too ;throw error:

![image](https://github.com/mfakane/rawinput-sharp/assets/33748890/37b93e17-27e7-43e4-a2d1-5e0b5f0035b2)
